---
output:
  pdf_document: default
  html_document: default
---

```{r}
#1. A.
Gender <- c("M","F","F","M","M","F")
ShoeSize <- c(8,6,7,9,10,6)
Height <- c(170,160,165,175,180,158)

df <- data.frame(Gender, ShoeSize, Height)
df

```

```{r}
#1. B.
males <- subset(df, Gender == "M")
females <- subset(df, Gender == "F")

males
females

```

```{r}
#1. C.
mean(df$ShoeSize)
mean(df$Height)

```



```{r}
#2.
months_vector <- c(
"March","April","January","November","January",
"September","October","September","November","August",
"January","November","November","February","May","August",
"July","December","August","August","September","November",
"February","April"
)

factor_months_vector <- factor(months_vector)
factor_months_vector

```

```{r}
#3.
summary(months_vector)
summary(factor_months_vector)

```

```{r}
#4.
factor_data <- c("East","West","West","West","West","North","North","North")

new_order_data <- factor(factor_data, levels = c("East","West","North"))
new_order_data

```





```{r}
#6.
search_number <- function(n) {
  if (n < 1 || n > 50) {
    print("The number selected is beyond the range of 1 to 50")
  } else if (n == 20) {
    print(TRUE)
  } else {
    print(n)
  }
}

search_number(sample(1:60, 1))

```


```{r}
#7.
min_bills <- function(price) {
  bills <- c(1000, 500, 200, 100, 50)
  count <- 0

  for (b in bills) {
    num <- price %/% b
    count <- count + num
    price <- price %% b
  }

  count
}

min_bills(1350)

```

```{r}
#8. A.
students <- data.frame(
Name = c("Annie","Thea","Steve","Hanna"),
Grade1 = c(85,65,75,95),
Grade2 = c(65,75,55,75),
Grade3 = c(85,90,80,100),
Grade4 = c(100,90,85,90)
)

students

```


```{r}
#8. B.
for (i in 1:nrow(students)) {
  avg <- (students[i,2] + students[i,3] + students[i,4] + students[i,5]) / 4
  if (avg > 90) {
    cat(students$Name[i], "average grade this semester is", avg, "\n")
  }
}

```


```{r}
#8. C.
for (j in 2:5) {
  avg <- (students[1,j] + students[2,j] + students[3,j] + students[4,j]) / 4
  if (avg < 80) {
    cat("The", j-1, "th test was difficult\n")
  }
}

```

```{r}
#8. D.
for (i in 1:nrow(students)) {
  highest <- students[i,2]
  for (j in 3:5) {
    if (students[i,j] > highest) {
      highest <- students[i,j]
    }
  }
  if (highest > 90) {
    cat(students$Name[i], "highest grade this semester is", highest, "\n")
  }
}

```

